# Generated by Django 3.1.4 on 2020-12-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
